#!/bin/bash
set -euo pipefail

# Script config
CMD_NAME="7d2d_server"
PROCESS_NAME="7DaysToDieServe" # first 15 chars of process, this depends on var GAME_BIN

# Game config
GAME_USER="steam"
GAME_DIR="/home/steam/7d2d"
GAME_BIN="$GAME_DIR/7DaysToDieServer.x86_64"
GAME_TELNET_IP="localhost"
GAME_TELNET_PORT="8081"
GAME_TELNET_PASSWORD=$(cat "$GAME_DIR"/telnet_password)
GAME_LOG_DIR="$GAME_DIR/7DaysToDieServer_Data/logs"
GAME_LOGFILE="$GAME_LOG_DIR/output_log_$(date +%Y-%m-%d__%H-%M-%S).log"
GAME_STARTUP_LOG="$GAME_LOG_DIR/startup_log_$(date +%Y-%m-%d__%H-%M-%S).log"
GAME_CONFIGFILE_LOCK="serverconfig.lock"
GAME_OPTS="-logfile $GAME_LOGFILE -quit -batchmode -nographics -dedicated"

start() {
    PID="$(get_pid)"
    if [[ "$PID" != "" ]]; then
        echo "Game server is already running"
    else
        echo "Starting game server..."
        local used_configfile=""

        if [[ $CONFIGFILE == "" ]]; then
            echo "No input for configfile, using configfile from lock $GAME_CONFIGFILE_LOCK: $(cat $GAME_DIR/$GAME_CONFIGFILE_LOCK)"
            used_configfile="$(cat $GAME_DIR/$GAME_CONFIGFILE_LOCK)"
        elif [[ -e "$GAME_DIR/$CONFIGFILE" ]]; then
            echo "Using configfile $CONFIGFILE from input"
            su -l $GAME_USER -c "echo $CONFIGFILE >$GAME_DIR/$GAME_CONFIGFILE_LOCK"
            used_configfile="$CONFIGFILE"
        else
            echo "configfile '$GAME_DIR/$CONFIGFILE' doesn't exist"
            exit 1
        fi

        set -x
        su -l $GAME_USER -c "nohup $GAME_BIN $GAME_OPTS -configfile=$used_configfile > $GAME_STARTUP_LOG 2>&1 &"
        set +x

        sleep 1

        PID="$(get_pid)"
        if [[ "$PID" != "" ]]; then
            echo "success"
        else
            echo "failure"
            cat $GAME_STARTUP_LOG
            exit 1
        fi
    fi
}

stop() {
    PID="$(get_pid)"
    if [[ "$PID" == "" ]]; then
        echo "Game server is already stopped"
    else
        echo "Stopping game server..."
        shutdown
    fi
}

reload() {
    PID="$(get_pid)"
    if [[ "$PID" == "" ]]; then
        echo "Game server is already stopped"
    else
        echo "Reloading game server..."
        eval "{ sleep 3; echo $GAME_TELNET_PASSWORD; sleep 3; echo 'say SERVER_EVENT_RESTART'; sleep 2; }"|telnet "$GAME_TELNET_IP" "$GAME_TELNET_PORT" || true
        sleep 3
        shutdown
        sleep 20
    fi

    start
}

shutdown() {
    eval "{ sleep 3; echo $GAME_TELNET_PASSWORD; sleep 3; echo 'lpi'; sleep 2; }"|telnet "$GAME_TELNET_IP" "$GAME_TELNET_PORT" || true
    sleep 3
    eval "{ sleep 3; echo $GAME_TELNET_PASSWORD; sleep 3; echo 'shutdown'; sleep 2; }"|telnet "$GAME_TELNET_IP" "$GAME_TELNET_PORT" || true
    sleep 10

    PID="$(get_pid)"
    if [[ "$PID" == "" ]]; then
        echo "Game server is already stopped"
    else
        sudo kill $PID
        if [[ "$?" != "0" ]]; then
            echo "Error shutting down game server with pid $PID: $?"
            exit "$?"
        fi
    fi
}

status() {
    PID="$(get_pid)"
    if [[ "$PID" == "" ]]; then
        echo "Game server is stopped, configfile locked to $(cat $GAME_DIR/$GAME_CONFIGFILE_LOCK)"
    else
        echo "Game server is running, configfile locked to $(cat $GAME_DIR/$GAME_CONFIGFILE_LOCK): $(ps -p $PID)"
        eval "{ sleep 3; echo $GAME_TELNET_PASSWORD; sleep 3; echo 'lpi'; sleep 3; }"|telnet "$GAME_TELNET_IP" "$GAME_TELNET_PORT" || true
    fi
}

get_pid() {
    set +e
    local PID=$(pgrep -u $GAME_USER -x $PROCESS_NAME)
    set -e

    echo $PID
}

set +u
COMMAND="$1"
CONFIGFILE="$2"
set -u

if [[ "$GAME_TELNET_PASSWORD" == "" ]]; then
    echo "Init error: Password for telnet server is empty"
    exit 1
fi

case "$COMMAND" in
  start)
        echo "DEBUG: configfile=$CONFIGFILE"
        start
        ;;
  stop)
        stop
        ;;
  reload)
        echo "DEBUG: configfile=$CONFIGFILE"
        reload
        ;;
  status)
        status
        ;;
  *)
        echo $"Usage: $CMD_NAME <command> <configfile> (<command> must be one of: start, stop, reload, status. <configfile> is optional)"
        exit 1
esac

exit 0
